// Presentation and filtering only; all counts and rates come from the read-only API.
(() => {
  const $=id=>document.getElementById('wr-'+id),providers={nojigiku:'のじぎく',tcg_meister:'TCGマイスター',sugatool:'スガツール'},formats={original:'オリジナル',advance:'アドバンス','2block':'2ブロック'};
  let data=null,scope=null,version=0,detailVersion=0,selected=null;
  const text=(tag,value,className)=>{const node=document.createElement(tag);node.textContent=value;if(className)node.className=className;return node;};
  const rate=value=>value===null?'—':value.toFixed(1)+'%';
  async function json(url){const response=await fetch(url,{cache:'no-store'}),body=await response.json();if(!response.ok||!body.success)throw Object.assign(Error(body.error||'読み込みに失敗しました。'),{status:response.status});return body;}
  function query(){const q=new URLSearchParams({mode:$('mode').value});if(q.get('mode')==='single')q.set('eventRecordId',$('event').value);for(const [id,key] of [['start','startDate'],['end','endDate'],['format','format'],['provider','provider']])if($(id).value)q.set(key,$(id).value);return q;}
  async function events(){const previous=$('event').value,result=await json('/api/winrate/events');$('event').replaceChildren(text('option','大会を選択'));$('event').firstChild.value='';for(const e of result.events){const option=text('option',`${e.date||'日付不明'} ${e.name||'大会名未取得'} ／ ${formats[e.format]||'形式未登録'} ／ ${e.providers.map(p=>providers[p]||p).join('・')}`);option.value=e.id;option.title=`ShopID:${e.shopId} / EventID:${e.eventId} / Seq:${e.seq}`;$('event').append(option);}$('event').value=previous;}
  function closeDetail(){detailVersion++;selected=null;$('detail').hidden=true;}
  async function reload(){const request=++version;closeDetail();data=null;$('results').hidden=true;$('status').textContent='集計中…';scope=query();try{if(scope.get('mode')==='single'&&!scope.get('eventRecordId')){ $('status').textContent='大会を選択してください。';return; }const result=await json('/api/winrate/summary?'+scope);if(request!==version)return;data=result;$('results').hidden=false;$('status').textContent=result.counts.savedRecords?`${result.events.length}大会を集計しました。デッキメモ変更後は再表示または再集計してください。`:'条件に一致する保存済み対戦表はありません。';render();}catch(e){if(request===version)$('status').textContent=e.message;}}
  function render(){const c=data.counts;$('counts').replaceChildren(...[['通常試合',c.normalMatches],['対面集計対象',c.matchupMatches],['対面集計対象外',c.excludedMatches],['重複除外後の全試合',c.uniqueMatches]].map(([label,n])=>{const card=text('div','', 'wr-count');card.append(text('span',label),text('strong',n));return card;}));
    $('exclusions').replaceChildren(...Object.entries({Bye:data.exclusions.bye,'両者敗北':data.exclusions.doubleLoss,'未判定':data.exclusions.unresolved,'デッキ未登録（通常試合）':data.exclusions.missingDeck,'その他（不正・競合）':data.exclusions.other,'うち保存元の競合':c.dedupConflicts,'重複として除外した保存記録':c.duplicatesRemoved}).map(([label,n])=>text('p',`${label}：${n}件`)));
    $('exclusions').append(text('p',`保存記録 ${c.savedRecords} − 重複 ${c.duplicatesRemoved} ＝ ${c.uniqueMatches}試合。対面対象 ${c.matchupMatches} ＋ 対象外 ${c.excludedMatches} ＝ ${c.uniqueMatches}試合。`));
    renderDecks();const ranges=Math.ceil(data.decks.length/20);$('axis').hidden=ranges<=1;for(const id of ['row-range','col-range']){const select=$(id);select.replaceChildren();for(let i=0;i<ranges;i++){const option=text('option',`${i*20+1}〜${Math.min((i+1)*20,data.decks.length)}件`);option.value=i;select.append(option);}}renderMatrix();}
  function ordered(){return [...data.decks].sort((a,b)=>$('sort').value==='name'?a.name.localeCompare(b.name,'ja'):$('sort').value==='rate'?(b.rate??-1)-(a.rate??-1)||b.matches-a.matches||a.name.localeCompare(b.name,'ja'):b.matches-a.matches||a.name.localeCompare(b.name,'ja'));}
  function renderDecks(){if(!data)return;$('decks').replaceChildren();for(const d of ordered()){const row=document.createElement('tr'),name=text('th',d.name);name.scope='row';name.title=d.name;row.append(name,...[d.matches,d.wins,d.losses,rate(d.rate)].map(n=>text('td',n)));$('decks').append(row);}if(!data.decks.length){const row=document.createElement('tr'),cell=text('td','デッキが登録された記録はありません。');cell.colSpan=5;row.append(cell);$('decks').append(row);}}
  function renderMatrix(){if(!data)return;const all=[...data.decks].sort((a,b)=>a.name.localeCompare(b.name,'ja')),rows=all.slice(Number($('row-range').value||0)*20,Number($('row-range').value||0)*20+20),cols=all.slice(Number($('col-range').value||0)*20,Number($('col-range').value||0)*20+20),pairs=new Map(data.pairs.map(p=>[p.deckId+':'+p.opponentDeckId,p]));
    const header=document.createElement('tr');header.append(text('th','使用デッキ ＼ 対面'));for(const d of cols){const h=text('th',d.name);h.scope='col';h.title=d.name;header.append(h);}$('matrix-head').replaceChildren(header);$('matrix-body').replaceChildren();
    for(const d of rows){const row=document.createElement('tr'),heading=text('th',d.name);heading.scope='row';heading.title=d.name;row.append(heading);for(const opp of cols){const cell=document.createElement('td'),p=pairs.get(d.deckId+':'+opp.deckId);if(p){const button=text('button','');button.type='button';button.dataset.deckId=d.deckId;button.dataset.opponentId=opp.deckId;button.setAttribute('aria-label',`${d.name} 対 ${opp.name} ${rate(p.rate)} ${p.matches}試合`);button.append(text('strong',rate(p.rate)),text('small',p.matches+'試合'));button.addEventListener('click',()=>openDetail(d.deckId,opp.deckId,1));cell.append(button);}else cell.textContent='—';row.append(cell);}$('matrix-body').append(row);}}
  async function openDetail(deckId,opponentDeckId,page){const request=++detailVersion,summary=data;if(!summary)return;selected={deckId,opponentDeckId,page};$('detail').hidden=false;$('detail-title').textContent='対面詳細';$('detail-status').textContent='読み込み中…';$('detail-matches').replaceChildren();$('prev').disabled=$('next').disabled=true;
    const q=new URLSearchParams(scope);for(const [k,v] of Object.entries({deckId,opponentDeckId,page,pageSize:50,revision:summary.revision}))q.set(k,v);
    try{const result=await json('/api/winrate/matchup?'+q);if(request!==detailVersion)return;const p=result.pair;$('detail-title').textContent=`${result.deck?.name||'デッキ'} 対 ${result.opponent?.name||'デッキ'}`;$('detail-status').textContent=`${p.matches}試合 ／ ${p.wins}勝 ${p.losses}敗 ／ ${rate(p.rate)}${deckId===opponentDeckId?'（ミラー：1試合につき2人分の成績）':''}`;
      for(const match of result.matches){const row=text('article','', 'wr-match');row.append(text('p',`${match.event.date||'日付不明'} ${match.event.name||'大会名未取得'} ／ ${providers[match.provider]} ／ ${match.round}回戦・卓${match.table??'不明'}`));row.append(text('p',match.sides.map(p=>`${p.name}（${p.deckName}）${p.participantKey===match.winnerKey?' 勝利':' 敗北'}`).join(' vs ')));row.append(text('small',`ShopID:${match.event.shopId} / EventID:${match.event.eventId} / Seq:${match.event.seq}`));const open=text('button','保存済み対戦表を開く');open.type='button';open.addEventListener('click',()=>openArchive(match.archiveId,match.round,open));row.append(open);$('detail-matches').append(row);}
      $('page').textContent=`${page} / ${Math.max(1,Math.ceil(result.total/result.pageSize))}ページ`;$('prev').disabled=page<=1;$('next').disabled=page*result.pageSize>=result.total;$('detail').scrollIntoView({block:'nearest'});
    }catch(e){if(request===detailVersion){$('detail-status').textContent=e.message;if(e.status===409){await reload();$('status').textContent='データ更新を検出し再集計しました。対面セルをもう一度選択してください。';}}}}
  async function openArchive(id,round,button){if(window.getMemoMatchingContext?.()?.busy){$('detail-status').textContent='デッキメモの処理完了後に開いてください。';return;}button.disabled=true;try{const [matching,decks]=await Promise.all([json('/api/matching-archives/'+id),json('/api/decks?sort=usage')]);if(window.getMemoMatchingContext?.()?.busy)throw Error('デッキメモの処理完了後に開いてください。');document.getElementById('menu-deck-memo').click();document.dispatchEvent(new CustomEvent('memo-open-matching-archive',{detail:{matching,decks:decks.decks,displayRound:round}}));}catch(e){$('detail-status').textContent=e.message;}finally{button.disabled=false;}}
  $('filters').addEventListener('submit',e=>{e.preventDefault();reload();});$('filters').addEventListener('change',()=>{$('event').disabled=$('mode').value!=='single';reload();});$('sort').addEventListener('change',renderDecks);for(const id of ['row-range','col-range'])$(id).addEventListener('change',renderMatrix);$('detail-close').addEventListener('click',closeDetail);for(const [id,delta] of [['prev',-1],['next',1]])$(id).addEventListener('click',()=>{if(selected)openDetail(selected.deckId,selected.opponentDeckId,selected.page+delta);});
  document.getElementById('menu-winrate').addEventListener('click',async()=>{hideAllPages();clearActiveMenus();document.getElementById('page-winrate').style.display='block';document.getElementById('menu-winrate').classList.add('active');const request=++version;closeDetail();$('results').hidden=true;$('status').textContent='大会一覧を読み込み中…';try{await events();if(request===version)await reload();}catch(e){if(request===version)$('status').textContent=e.message;}});
})();
