// Presentation and filtering only; all counts and rates come from the read-only API.
(() => {
  const $=id=>document.getElementById('wr-'+id),providers={nojigiku:'のじぎく',tcg_meister:'TCGマイスター',sugatool:'スガツール'},formats={original:'オリジナル',advance:'アドバンス','2block':'2ブロック'};
  let data=null,scope=null,version=0,detailVersion=0,selected=null,catalog=[];
  const text=(tag,value,className)=>{const node=document.createElement(tag);node.textContent=value;if(className)node.className=className;return node;};
  const rate=value=>value===null?'—':value.toFixed(1)+'%';
  async function json(url){const response=await fetch(url,{cache:'no-store'}),body=await response.json();if(!response.ok||!body.success)throw Object.assign(Error(body.error||'読み込みに失敗しました。'),{status:response.status});return body;}
  function query(){const q=new URLSearchParams({mode:$('mode').value});if(q.get('mode')==='single')q.set('eventRecordId',$('event').value);for(const [id,key] of [['start','startDate'],['end','endDate'],['format','format'],['provider','provider']])if($(id).value)q.set(key,$(id).value);if($('search-mode').value!=='all'){q.set('searchMode',$('search-mode').value);q.set('deckAId',$('deck-a').value);if($('search-mode').value==='matchup')q.set('deckBId',$('deck-b').value);}return q;}
  async function events(){const previous=$('event').value,result=await json('/api/winrate/events');$('event').replaceChildren(text('option','大会を選択'));$('event').firstChild.value='';for(const e of result.events){const option=text('option',`${e.date||'日付不明'} ${e.name||'大会名未取得'} ／ ${formats[e.format]||'形式未登録'} ／ ${e.providers.map(p=>providers[p]||p).join('・')}`);option.value=e.id;option.title=`ShopID:${e.shopId} / EventID:${e.eventId} / Seq:${e.seq}`;$('event').append(option);}$('event').value=previous;}
  function choices(which){const select=$('deck-'+which),previous=select.value,term=$('deck-'+which+'-query').value.trim().toLowerCase(),available=catalog.filter(d=>[d.name,...(d.aliases||[])].some(name=>name.toLowerCase().includes(term)));select.replaceChildren(text('option','デッキを選択'));select.firstChild.value='';for(const d of available){const option=text('option',d.name);option.value=d.id;select.append(option);}if(previous&&!available.some(d=>String(d.id)===previous)){const d=catalog.find(d=>String(d.id)===previous);if(d){const option=text('option',d.name+'（選択中）');option.value=d.id;select.append(option);}}select.value=previous;$('deck-'+which+'-hint').textContent=available.length?available.length+'件の候補':'一致するデッキ候補がありません';}
  async function deckChoices(){const result=await json('/api/decks');catalog=result.decks;choices('a');choices('b');}
  function searchFields(){$('deck-a-field').hidden=$('search-mode').value==='all';$('deck-b-field').hidden=$('search-mode').value!=='matchup';}
  function closeDetail(){detailVersion++;selected=null;$('detail').hidden=true;}
  async function reload(){const request=++version;closeDetail();data=null;$('results').hidden=true;$('status').textContent='集計中…';scope=query();try{if(scope.get('mode')==='single'&&!scope.get('eventRecordId')){ $('status').textContent='大会を選択してください。';return; }if(scope.has('searchMode')&&(!scope.get('deckAId')||(scope.get('searchMode')==='matchup'&&!scope.get('deckBId')))){$('status').textContent='検索するデッキ'+(!scope.get('deckAId')?'A':'B')+'を選択してください。';return;}const result=await json('/api/winrate/summary?'+scope);if(request!==version)return;data=result;$('results').hidden=false;$('status').textContent=result.search&&result.search.stats.matches===0?'該当する対戦データがありません。':result.counts.savedRecords?`${result.search?result.search.events.length:result.events.length}大会を集計しました。デッキメモ変更後は再表示または再集計してください。`:'条件に一致する保存済み対戦表はありません。';render();}catch(e){if(request===version)$('status').textContent=e.message;}}
  function render(){const c=data.counts;$('counts').replaceChildren(...[['通常試合',c.normalMatches],['対面集計対象',c.matchupMatches],['対面集計対象外',c.excludedMatches],['重複除外後の全試合',c.uniqueMatches]].map(([label,n])=>{const card=text('div','', 'wr-count');card.append(text('span',label),text('strong',n));return card;}));
    $('exclusions').replaceChildren(...Object.entries({Bye:data.exclusions.bye,'両者敗北':data.exclusions.doubleLoss,'未判定':data.exclusions.unresolved,'デッキ未登録（通常試合）':data.exclusions.missingDeck,'その他（不正・競合）':data.exclusions.other,'うち保存元の競合':c.dedupConflicts,'重複として除外した保存記録':c.duplicatesRemoved}).map(([label,n])=>text('p',`${label}：${n}件`)));
    $('exclusions').append(text('p',`保存記録 ${c.savedRecords} − 重複 ${c.duplicatesRemoved} ＝ ${c.uniqueMatches}試合。対面対象 ${c.matchupMatches} ＋ 対象外 ${c.excludedMatches} ＝ ${c.uniqueMatches}試合。`));
    renderSearch();renderDecks();const ranges=Math.ceil(data.decks.length/20);$('axis').hidden=ranges<=1||data.search?.mode==='matchup';$('row-range').parentElement.hidden=Boolean(data.search);$('col-range').parentElement.hidden=data.search?.mode==='matchup';for(const id of ['row-range','col-range']){const select=$(id);select.replaceChildren();for(let i=0;i<ranges;i++){const option=text('option',`${i*20+1}〜${Math.min((i+1)*20,data.decks.length)}件`);option.value=i;select.append(option);}}renderMatrix();}
  function ordered(){return [...data.decks].sort((a,b)=>$('sort').value==='name'?a.name.localeCompare(b.name,'ja'):$('sort').value==='rate'?(b.rate??-1)-(a.rate??-1)||b.matches-a.matches||a.name.localeCompare(b.name,'ja'):b.matches-a.matches||a.name.localeCompare(b.name,'ja'));}
  function renderDecks(){if(!data)return;$('decks').replaceChildren();for(const d of ordered().filter(d=>!data.search||d.deckId===data.search.deck?.id)){const row=document.createElement('tr'),name=text('th',d.name);name.scope='row';name.title=d.name;row.append(name,...[d.matches,d.wins,d.losses,rate(d.rate)].map(n=>text('td',n)));$('decks').append(row);}if(!data.decks.length){const row=document.createElement('tr'),cell=text('td',data.search?'該当する対戦データがありません。':'デッキが登録された記録はありません。');cell.colSpan=5;row.append(cell);$('decks').append(row);}}
  function renderMatrix(){if(!data)return;const all=[...data.decks].sort((a,b)=>a.name.localeCompare(b.name,'ja')),rows=(data.search?all.filter(d=>d.deckId===data.search.deck?.id):all).slice(Number($('row-range').value||0)*20,Number($('row-range').value||0)*20+20),cols=(data.search?.mode==='matchup'?all.filter(d=>d.deckId===data.search.opponent?.id):all).slice(Number($('col-range').value||0)*20,Number($('col-range').value||0)*20+20),pairs=new Map(data.pairs.map(p=>[p.deckId+':'+p.opponentDeckId,p]));
    const header=document.createElement('tr');header.append(text('th','使用デッキ ＼ 対面'));for(const d of cols){const h=text('th',d.name);h.scope='col';h.title=d.name;header.append(h);}$('matrix-head').replaceChildren(header);$('matrix-body').replaceChildren();
    for(const d of rows){const row=document.createElement('tr'),heading=text('th',d.name);heading.scope='row';heading.title=d.name;row.append(heading);for(const opp of cols){const cell=document.createElement('td'),p=pairs.get(d.deckId+':'+opp.deckId);if(p){const button=text('button','');button.type='button';button.dataset.deckId=d.deckId;button.dataset.opponentId=opp.deckId;button.setAttribute('aria-label',`${d.name} 対 ${opp.name} ${rate(p.rate)} ${p.matches}試合`);button.append(text('strong',rate(p.rate)),text('small',p.matches+'試合'));button.addEventListener('click',()=>openDetail(d.deckId,opp.deckId,1));cell.append(button);}else cell.textContent='—';row.append(cell);}$('matrix-body').append(row);}}
  function renderSearch(){const search=data.search;$('search-results').hidden=!search;if(!search)return;const p=search.stats;$('search-title').textContent=search.deck?.name+(search.mode==='matchup'?' 対 '+search.opponent?.name:'の戦績');$('search-stats').textContent=`${p.matches}試合 ／ ${p.wins}勝 ${p.losses}敗 ／ ${rate(p.rate)}（勝率の分母：${p.observations}人分）`;
    const unknown=search.unknownOpponent;$('search-gap').textContent=`相手デッキ不明で対面別一覧に含まれない成績：${unknown.matches}試合・${unknown.wins}勝${unknown.losses}敗。相手判明の対面は${p.matches-unknown.matches}試合。Bye・両者敗北・未判定は下の除外件数を参照してください。`;$('search-details').disabled=p.matches===0;
    $('search-opponents').replaceChildren();for(const pair of search.opponents){const row=document.createElement('tr'),name=data.decks.find(d=>d.deckId===pair.opponentDeckId)?.name||'不明';row.append(...[name,pair.matches,pair.wins,pair.losses,rate(pair.rate)].map(v=>text('td',v)));const cell=document.createElement('td'),button=text('button','詳細');button.type='button';button.addEventListener('click',()=>openDetail(pair.deckId,pair.opponentDeckId,1));cell.append(button);row.append(cell);$('search-opponents').append(row);}
    $('search-events').replaceChildren();for(const item of search.events){const row=document.createElement('tr');row.append(...[`${item.event.date||'日付不明'} ${item.event.name||'大会名未取得'}`,item.matches,item.wins,item.losses,rate(item.rate)].map(v=>text('td',v)));row.firstChild.title=`ShopID:${item.event.shopId} / EventID:${item.event.eventId} / Seq:${item.event.seq}`;$('search-events').append(row);}
    for(const id of ['search-opponents','search-events'])if(!$(id).children.length){const row=document.createElement('tr'),cell=text('td','該当する対戦データがありません。');cell.colSpan=id==='search-opponents'?6:5;row.append(cell);$(id).append(row);}
  }
  async function openDetail(deckId,opponentDeckId,page){const request=++detailVersion,summary=data;if(!summary)return;selected={deckId,opponentDeckId,page};$('detail').hidden=false;$('detail-title').textContent='対面詳細';$('detail-status').textContent='読み込み中…';$('detail-matches').replaceChildren();$('prev').disabled=$('next').disabled=true;
    const isSearch=deckId===null,q=new URLSearchParams(scope);for(const [k,v] of Object.entries({...(!isSearch?{deckId,opponentDeckId}:{}),page,pageSize:50,revision:summary.revision}))q.set(k,v);
    try{const result=await json((isSearch?'/api/winrate/search-matches?':'/api/winrate/matchup?')+q);if(request!==detailVersion)return;const p=isSearch?result.search.stats:result.pair;$('detail-title').textContent=isSearch?result.search.deck?.name+'の検索詳細':`${result.deck?.name||'デッキ'} 対 ${result.opponent?.name||'デッキ'}`;$('detail-status').textContent=`${p.matches}試合 ／ ${p.wins}勝 ${p.losses}敗 ／ ${rate(p.rate)}${!isSearch&&deckId===opponentDeckId?'（ミラー：1試合につき2人分の成績）':''}`;
      for(const match of result.matches){const row=text('article','', 'wr-match');row.append(text('p',`${match.event.date||'日付不明'} ${match.event.name||'大会名未取得'} ／ ${providers[match.provider]} ／ ${match.round}回戦・卓${match.table??'不明'}`));row.append(text('p',match.sides.map(p=>`${p.name}（${p.deckName||'デッキ不明'}）${p.participantKey===match.winnerKey?' 勝利':' 敗北'}`).join(' vs ')));row.append(text('small',`ShopID:${match.event.shopId} / EventID:${match.event.eventId} / Seq:${match.event.seq}`));const open=text('button','保存済み対戦表を開く');open.type='button';open.addEventListener('click',()=>openArchive(match.archiveId,match.round,open));row.append(open);$('detail-matches').append(row);}
      $('page').textContent=`${page} / ${Math.max(1,Math.ceil(result.total/result.pageSize))}ページ`;$('prev').disabled=page<=1;$('next').disabled=page*result.pageSize>=result.total;$('detail').scrollIntoView({block:'nearest'});
    }catch(e){if(request===detailVersion){$('detail-status').textContent=e.message;if(e.status===409){await reload();$('status').textContent='データ更新を検出し再集計しました。対面セルをもう一度選択してください。';}}}}
  async function openArchive(id,round,button){if(window.getMemoMatchingContext?.()?.busy){$('detail-status').textContent='デッキメモの処理完了後に開いてください。';return;}button.disabled=true;try{const [matching,decks]=await Promise.all([json('/api/matching-archives/'+id),json('/api/decks?sort=usage')]);if(window.getMemoMatchingContext?.()?.busy)throw Error('デッキメモの処理完了後に開いてください。');document.getElementById('menu-deck-memo').click();document.dispatchEvent(new CustomEvent('memo-open-matching-archive',{detail:{matching,decks:decks.decks,displayRound:round}}));}catch(e){$('detail-status').textContent=e.message;}finally{button.disabled=false;}}
  $('filters').addEventListener('submit',e=>{e.preventDefault();reload();});$('filters').addEventListener('change',event=>{if(event.target.id.endsWith('-query'))return;searchFields();$('event').disabled=$('mode').value!=='single';reload();});$('sort').addEventListener('change',renderDecks);for(const id of ['row-range','col-range'])$(id).addEventListener('change',renderMatrix);$('detail-close').addEventListener('click',closeDetail);for(const [id,delta] of [['prev',-1],['next',1]])$(id).addEventListener('click',()=>{if(selected)openDetail(selected.deckId,selected.opponentDeckId,selected.page+delta);});
  for(const which of ['a','b'])$('deck-'+which+'-query').addEventListener('input',()=>choices(which));
  $('search-details').addEventListener('click',()=>openDetail(null,null,1));
  $('search-clear').addEventListener('click',()=>{$('search-mode').value='all';for(const which of ['a','b']){$('deck-'+which+'-query').value='';$('deck-'+which).value='';choices(which);}searchFields();reload();});
  document.getElementById('menu-winrate').addEventListener('click',async()=>{hideAllPages();clearActiveMenus();document.getElementById('page-winrate').style.display='block';document.getElementById('menu-winrate').classList.add('active');const request=++version;closeDetail();$('results').hidden=true;$('status').textContent='大会一覧を読み込み中…';try{await Promise.all([events(),deckChoices()]);searchFields();if(request===version)await reload();}catch(e){if(request===version)$('status').textContent=e.message;}});
})();
