// Isolated database. Only local fixture-backed APIs are reachable.
const {chromium}=require('playwright'),express=require('express'),assert=require('node:assert/strict'),path=require('node:path');
const {fixture}=require('./matching-archives-postgres.integration'),{seed}=require('./winrate-postgres.integration');
(async()=>{
 const f=await fixture();await seed(f);
 await f.db.exec(`INSERT INTO matching_archives(event_record_id,provider,source_key,source_url) VALUES(1,'tcg_meister','other-source','fixture');
 INSERT INTO matching_archive_matches(archive_id,round,match_key,table_no,sides,outcome,winner_key) SELECT 4,round,match_key,table_no,sides,outcome,winner_key FROM matching_archive_matches WHERE archive_id=1;
 INSERT INTO event_results(event_record_id,player_id,rank) VALUES(1,1,1);
 INSERT INTO deck_history(player_id,shop_id,event_id,seq,event_date,deck_name) VALUES(1,'s','e','1','2026-10-01','A');`);
 const protectedTables=['events','event_results','players','deck_memo_events','deck_memos','deck_memo_external_players','deck_memo_roster','deck_memo_archives','deck_memo_archive_players','deck_history'];
 const snapshot=()=>Promise.all(protectedTables.map(t=>f.db.query('SELECT * FROM '+t+' ORDER BY 1').then(r=>r.rows)));const before=await snapshot();
 const app=express();app.use(express.json());const requests=[];let failDelete=false,releaseRequest=null,delayDelete=false;
 for(const [key,handler]of f.routes){const [method,...parts]=key.split(' ');app[method.toLowerCase()](parts.join(' '),key==='POST /api/matching-archives/:id/delete'?async(req,res)=>{requests.push({id:req.params.id,body:req.body});if(failDelete){res.status(500).json({success:false,error:'テスト削除失敗'});return;}if(delayDelete)await new Promise(resolve=>{releaseRequest=resolve;});await handler(req,res);}:handler);}app.use(express.static(path.resolve(__dirname,'..')));
 const server=await new Promise(r=>{const s=app.listen(0,'127.0.0.1',()=>r(s));});let browser;
 try{
  browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_EXECUTABLE||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});const page=await browser.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route('**/*',r=>new URL(r.request().url()).hostname==='127.0.0.1'?r.continue():r.abort());await page.goto('http://127.0.0.1:'+server.address().port);
  for(const width of [375,390,430,768,1440]){
   await page.setViewportSize({width,height:900});await page.locator('#menu-deck-memo').click();await page.waitForFunction(()=>document.querySelectorAll('.matching-archive-row').length===4);assert.equal(await page.locator('#matching-archive-list .danger-button').count(),0);assert.equal(await page.locator('#matching-delete-open.danger-button').count(),0);
   await page.locator('#matching-delete-open').click();await page.waitForFunction(()=>document.querySelectorAll('#matching-delete-events button').length===3);assert.equal(requests.length,0);
   await page.locator('#matching-delete-events button[data-archive-ids="2"]').click();assert.equal(await page.locator('#matching-delete-confirm').isVisible(),true);assert.ok((await page.locator('#matching-delete-event').textContent()).includes('2026-10-02'));assert.equal(requests.length,0);await page.locator('#matching-delete-cancel').click();assert.equal(await page.locator('#matching-delete-dialog').isVisible(),false);
   await page.locator('#matching-delete-open').click();await page.locator('#matching-delete-events button').filter({hasText:'のじぎく大会'}).click();assert.equal(await page.locator('#matching-delete-archives input').count(),2);assert.equal(await page.locator('#matching-delete-execute').isEnabled(),false);await page.locator('#matching-delete-archives input[value="4"]').check();assert.equal(requests.length,0);assert.equal(await page.locator('#matching-delete-execute').isEnabled(),true);
   await page.screenshot({path:'/tmp/matching-delete-'+width+'.png',fullPage:true});assert.ok(await page.locator('#matching-delete-dialog').evaluate(n=>n.getBoundingClientRect().width<=innerWidth));await page.keyboard.press('Escape');assert.equal(await page.locator('#matching-delete-dialog').isVisible(),false);assert.equal((await f.db.query('SELECT count(*)::int n FROM matching_archives')).rows[0].n,4);
   console.log('PASS '+width+'px: separated delete control, grouped events, explicit archive, select/cancel preserves data and modal layout');
  }
  await page.locator('#menu-winrate').click();await page.waitForFunction(()=>!document.querySelector('#wr-results').hidden);assert.equal(await page.locator('#wr-provider').count(),0);assert.equal(await page.locator('#wr-counts strong').nth(1).textContent(),'6');assert.ok(!(await page.locator('#wr-event').textContent()).includes('TCGマイスター'));await page.locator('#wr-matrix-body button').first().click();await page.waitForFunction(()=>document.querySelectorAll('#wr-detail-matches article').length===6);assert.ok(!(await page.locator('#wr-detail-matches').textContent()).includes('スガツール'));
  await page.locator('#menu-deck-memo').click();await page.locator('#matching-delete-open').click();await page.locator('#matching-delete-events button').filter({hasText:'のじぎく大会'}).click();await page.locator('#matching-delete-archives input[value="4"]').check();failDelete=true;await page.locator('#matching-delete-execute').click();await page.waitForFunction(()=>document.querySelector('#matching-delete-status').textContent==='テスト削除失敗');assert.equal(await page.locator('.matching-archive-row').count(),4);assert.equal((await f.db.query('SELECT count(*)::int n FROM matching_archives')).rows[0].n,4);
  failDelete=false;delayDelete=true;await page.evaluate(()=>{document.getElementById('matching-delete-execute').click();document.getElementById('matching-delete-execute').click();});await page.waitForFunction(()=>document.querySelector('#matching-delete-status').textContent.includes('削除中'));while(!releaseRequest)await new Promise(r=>setTimeout(r,10));assert.equal(requests.length,2);assert.equal(await page.locator('#matching-delete-cancel').isEnabled(),false);await page.keyboard.press('Escape');assert.equal(await page.locator('#matching-delete-dialog').isVisible(),true);releaseRequest();delayDelete=false;
  await page.waitForFunction(()=>document.querySelector('#matching-delete-status').textContent.includes('アーカイブ #4を削除しました'));assert.equal(await page.locator('.matching-archive-row').count(),3);assert.equal((await f.db.query('SELECT id FROM matching_archives WHERE id=1')).rows.length,1);assert.deepEqual(requests[1].body,{confirmed:true,shopId:'s',eventId:'e',seq:'1'});await page.locator('#matching-delete-cancel').click();
  await page.locator('#menu-winrate').click();await page.waitForFunction(()=>!document.querySelector('#wr-results').hidden);assert.equal(await page.locator('#wr-counts strong').nth(1).textContent(),'6');
  await page.locator('#menu-deck-memo').click();await page.locator('#matching-delete-open').click();await page.locator('#matching-delete-events button[data-archive-ids="1"]').click();await page.locator('#matching-delete-execute').click();await page.waitForFunction(()=>document.querySelectorAll('.matching-archive-row').length===2);await page.locator('#matching-delete-cancel').click();
  await page.locator('#menu-winrate').click();await page.waitForFunction(()=>!document.querySelector('#wr-results').hidden);assert.equal(await page.locator('#wr-counts strong').nth(1).textContent(),'4');assert.deepEqual(await snapshot(),before);assert.deepEqual((await f.db.query('SELECT id FROM matching_archives ORDER BY id')).rows.map(r=>r.id),[2,3]);
  // Empty archive list is a normal, non-destructive state. Override GET only, not database contents.
  await page.route('**/api/matching-archives',route=>route.fulfill({json:{success:true,archives:[]}}));await page.locator('#menu-deck-memo').click();await page.locator('#matching-delete-open').click();await page.waitForFunction(()=>document.querySelector('#matching-delete-events').textContent.includes('削除対象の保存済み対戦表はありません'));assert.equal(await page.locator('#matching-delete-confirm').isVisible(),false);await page.locator('#matching-delete-cancel').click();assert.equal(requests.length,3);
  assert.deepEqual(errors,[]);console.log('PASS deletion failure preserves list, double-click guard, exact single archive deletion, protected tables, all-source analysis freshness and empty state');
 }finally{await browser?.close();await new Promise(r=>server.close(r));await f.db.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
