// Isolated PostgreSQL + local Chrome. Never accesses production DB or external sites.
const {chromium}=require('playwright'),express=require('express'),assert=require('node:assert/strict'),path=require('node:path');
const {fixture}=require('./matching-archives-postgres.integration');
(async()=>{
 const f=await fixture();await f.db.exec("INSERT INTO rock_paper_scissors_records(player_id,hand) VALUES(1,'rock');");const original=(await f.db.query('SELECT * FROM rock_paper_scissors_records WHERE id=1')).rows;
 const app=express();app.use(express.json());for(const [key,h]of f.routes){const [method,...parts]=key.split(' ');app[method.toLowerCase()](parts.join(' '),h);}app.use(express.static(path.resolve(__dirname,'..')));const server=await new Promise(r=>{const s=app.listen(0,'127.0.0.1',()=>r(s));});let browser;
 try{
  browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_EXECUTABLE||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});const page=await browser.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route('**/*',r=>new URL(r.request().url()).hostname==='127.0.0.1'?r.continue():r.abort());
  async function selectPlayer(width){if(width<=720)await page.locator('#menu-more').click();await page.locator('#menu-rps').click();await page.locator('#rps-player-name').fill('000123');await page.locator('#rps-search').click();await page.locator('#rps-candidates button').filter({hasText:'DMP ID：000123'}).click();}
  async function saved(){await page.waitForFunction(()=>!document.getElementById('rps-form').hasAttribute('aria-busy')&&document.getElementById('rps-status').textContent.includes('保存しました'));}
  for(const width of [375,390,430,768,1440]){
   await page.setViewportSize({width,height:900});await page.goto('http://127.0.0.1:'+server.address().port);await selectPlayer(width);assert.equal(await page.locator('#rps-ties select').count(),0);
   await page.locator('#rps-hand').selectOption('scissors');await page.locator('#rps-tie-add').click();await page.locator('#rps-ties select').nth(0).selectOption('rock');await page.locator('#rps-tie-add').click();await page.locator('#rps-ties select').nth(1).selectOption('paper');await page.locator('#rps-save').click();await page.waitForFunction(()=>document.querySelector('#rps-status').textContent.includes('記録しました'));assert.equal(await page.locator('#rps-ties select').count(),0);
   await page.locator('#rps-history-load').click();await page.waitForFunction(()=>document.querySelectorAll('.rps-history-record').length>0);await page.locator('.rps-history-record button').first().click();assert.deepEqual(await page.locator('#rps-ties select').evaluateAll(nodes=>nodes.map(n=>n.value)),['rock','paper']);
   await page.locator('#rps-tie-add').click();await page.locator('#rps-ties select').nth(2).selectOption('scissors');await page.locator('#rps-ties select').nth(0).selectOption('paper');await page.locator('#rps-ties button').nth(1).click();assert.deepEqual(await page.locator('#rps-ties label').allTextContents(),['1回目のあいこ','2回目のあいこ']);await page.locator('#rps-hand').selectOption('rock');await page.locator('#rps-save').click();await saved();
   await page.reload();await selectPlayer(width);await page.locator('#rps-history-load').click();await page.waitForFunction(()=>document.querySelectorAll('.rps-history-record').length>0);await page.locator('.rps-history-record button').first().click();assert.deepEqual(await page.locator('#rps-ties select').evaluateAll(nodes=>nodes.map(n=>n.value)),['paper','scissors']);assert.equal(await page.locator('#rps-hand').inputValue(),'rock');await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:'/tmp/rps-ties-form-'+width+'.png',fullPage:true});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await page.locator('#rps-edit-cancel').click();
   await page.locator('#rps-view-player').click();await page.waitForFunction(()=>document.querySelectorAll('.rps-tie-stage').length===3);assert.ok((await page.locator('.rps-tie-stage').nth(0).textContent()).includes('チョキ'));assert.ok((await page.locator('.rps-tie-stage').nth(1).textContent()).includes('グー'));assert.ok((await page.locator('.rps-tie-stage').nth(2).textContent()).includes('データなし'));assert.equal(await page.locator('#player-rps-stats > div').count(),3);await page.screenshot({path:'/tmp/rps-ties-predictions-'+width+'.png',fullPage:true});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));console.log('PASS '+width+'px: ordered optional ties, add/remove/reindex, save/edit, reload persistence, stages and layout');
  }
  assert.deepEqual((await f.db.query('SELECT * FROM rock_paper_scissors_records WHERE id=1')).rows,original);assert.deepEqual(errors,[]);console.log('PASS original final-hand records untouched and no page errors');
 }finally{await browser?.close();await new Promise(r=>server.close(r));await f.db.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
