const {test}=require('node:test'),assert=require('node:assert/strict');
const {aggregate,filters}=require('../winrate-analysis');
const catalog=[{id:1,name:'ゴルギーオージャー',aliases:['ゴルギー']},{id:2,name:'生徒会',aliases:[]},{id:3,name:'未使用',aliases:[]}];
const side=(key,deckId,dmpId=null)=>({participantKey:key,deckId,dmpId,name:'　同名'});
function match(options={}){return {archiveId:1,provider:'nojigiku',sourceKey:'one',event:{id:1,shopId:'s',eventId:'e',seq:'1',name:'大会',date:'2026-10-10'},round:1,table:1,matchKey:'one',sides:[side('entry:1',1,'100'),side('entry:2',2,'200')],winnerKey:'entry:1',outcome:'win_loss',...options};}
const deck=(r,id)=>r.decks.find(d=>d.deckId===id),pair=(r,a,b)=>r.pairs.find(p=>p.deckId===a&&p.opponentDeckId===b);
test('three providers, multiple event and round totals, deterministic fresh aggregation',()=>{const rows=['nojigiku','tcg_meister','sugatool'].map((provider,i)=>match({provider,archiveId:i+1,event:{id:i+1},round:i+1}));const r=aggregate(rows,catalog);assert.equal(r.counts.uniqueMatches,3);assert.equal(deck(r,1).wins,3);assert.equal(pair(r,2,1).rate,0);assert.deepEqual(aggregate(rows,catalog),r);assert.equal(rows[0].sides[0].deckId,1);});
test('mirror physical count one, two player observations, directional detail matches totals',()=>{const r=aggregate([match({sides:[side('entry:1',1),side('entry:2',1)]})],catalog);assert.equal(r.counts.matchupMatches,1);assert.equal(deck(r,1).matches,2);assert.equal(deck(r,1).physicalMatches,1);assert.equal(pair(r,1,1).matches,1);assert.equal(pair(r,1,1).rate,50);assert.equal(r.detail.get('1:1').length,1);});
test('exclusive exclusions, unknown opponent counts known-side deck only, zero-rate is null',()=>{const rows=[match({outcome:'bye'}),match({outcome:'double_loss',round:2}),match({outcome:'unresolved',round:3}),match({sides:[side('entry:1',1),side('entry:2',null)],round:4}),match({outcome:'unknown',round:5,sides:[side('entry:1',3),side('entry:2',null)]})];const r=aggregate(rows,catalog);assert.deepEqual(r.exclusions,{bye:1,doubleLoss:1,unresolved:1,missingDeck:1,other:1});assert.equal(r.counts.uniqueMatches,r.counts.matchupMatches+r.counts.excludedMatches);assert.equal(deck(r,1).wins,1);assert.equal(deck(r,3).rate,null);assert.equal(r.pairs.length,0);});
test('invalid winner, same player, malformed sides and unknown provider never counted',()=>{for(const m of [match({winnerKey:'absent'}),match({sides:[side('same',1),side('same',2)]}),match({sides:[side('a',1,'123'),side('b',2,'123')]}),match({sides:[]}),match({provider:'unknown'})])assert.equal(aggregate([m],catalog).exclusions.other,1);});
test('canonical IDs and exact aliases unify, similar or whitespace names do not',()=>{const r=aggregate([match({sides:[{...side('entry:1',null),deckName:'ゴルギー'},side('entry:2',2)]})],catalog);assert.equal(deck(r,1).wins,1);for(const name of [' ゴルギー','ゴルギーX'])assert.equal(aggregate([match({sides:[{...side('entry:1',null),deckName:name},side('entry:2',2)]})],catalog).exclusions.missingDeck,1);});
test('official name has priority over alias; aliases resolve by lowest ID',()=>{const cats=[{id:1,name:'A',aliases:['B','x']},{id:2,name:'B',aliases:['x']}];const r=aggregate([match({sides:[{...side('entry:1',null),deckName:'b'},side('entry:2',2)]})],cats);assert.equal(r.pairs[0].deckId,2);assert.equal(r.pairs[0].opponentDeckId,2);});
test('certain cross-provider DMP duplicate deduplicates reversed rows, detail once',()=>{const a=match(),b=match({archiveId:2,provider:'sugatool',matchKey:'uuid',sides:[side('other2',2,'200'),side('other1',1,'100')],winnerKey:'other1'});const r=aggregate([a,b],catalog);assert.equal(r.counts.duplicatesRemoved,1);assert.equal(r.counts.matchupMatches,1);assert.equal(r.detail.get('1:2')[0].sources.length,2);});
test('name-only and local number across source/tournament never merge',()=>{const a=match({sides:[side('id:39',1),side('id:53',2)],winnerKey:'id:39',provider:'tcg_meister'});for(const changes of [{archiveId:2,sourceKey:'other'},{archiveId:2,provider:'sugatool'},{archiveId:2,event:{id:2}}])assert.equal(aggregate([a,{...a,...changes}],catalog).counts.uniqueMatches,2);const ambiguous=match({sides:[side('seat:1:1:1',1),side('seat:1:1:2',2)],winnerKey:'seat:1:1:1'});assert.equal(aggregate([ambiguous,{...ambiguous,archiveId:2}],catalog).counts.uniqueMatches,2);});
test('confirmed outcome wins over unresolved duplicate, contradictory outcomes excluded',()=>{const a=match(),b=match({archiveId:2,outcome:'unresolved'});assert.equal(aggregate([a,b],catalog).counts.matchupMatches,1);for(const copy of [match({archiveId:2,winnerKey:'entry:2'}),match({archiveId:2,outcome:'double_loss'}),match({archiveId:2,sides:[side('entry:1',2,'100'),side('entry:2',2,'200')]})]){const r=aggregate([a,copy],catalog);assert.equal(r.exclusions.other,1);assert.equal(r.counts.dedupConflicts,1);assert.equal(r.counts.matchupMatches,0);}});
test('different rounds and event Seq preserved, side IDs never coerced into number',()=>{const a=match();assert.equal(aggregate([a,{...a,round:2},{...a,event:{id:2,seq:'2'}},match({archiveId:3,sides:[side('entry:1',1,'0100'),side('entry:2',2,'200')]})],catalog).counts.uniqueMatches,4);});
test('memo updates are reflected without changing original input',()=>{const a=match();const first=aggregate([a],catalog);a.sides[0].deckId=2;const second=aggregate([a],catalog);assert.equal(first.pairs[0].deckId,1);assert.equal(second.pairs[0].rate,50);});
test('filter validation includes combined scopes, real dates and rejects ambiguous inputs',()=>{assert.deepEqual(filters({mode:'single',eventRecordId:'1',startDate:'2026-10-01',endDate:'2026-10-10',format:'original',provider:'sugatool'}),{mode:'single',eventRecordId:1,startDate:'2026-10-01',endDate:'2026-10-10',format:'original',provider:'sugatool'});for(const q of [{mode:'single'},{mode:'other'},{eventRecordId:'1'},{mode:'single',eventRecordId:'1 OR 1=1'},{startDate:'2026-02-30'},{startDate:'2026-10-11',endDate:'2026-10-10'},{format:'x'},{provider:['nojigiku','sugatool']}])assert.throws(()=>filters(q));});

test('Bye DMP identity deduplicates across providers; date year zero rejected',()=>{const a=match({outcome:'bye',sides:[side('dmp:100',1,'100')]}),b={...a,archiveId:2,provider:'sugatool',sides:[side('uuid',1,'100')]};const r=aggregate([a,b],catalog);assert.equal(r.exclusions.bye,1);assert.equal(r.counts.duplicatesRemoved,1);assert.throws(()=>filters({startDate:'0000-01-01'}));});
