// Isolated PostgreSQL + local Chrome; no external pairings or production database access.
const {chromium}=require('playwright'),express=require('express'),assert=require('node:assert/strict'),path=require('node:path');
const {fixture}=require('./matching-archives-postgres.integration'),{seed}=require('./winrate-postgres.integration');
(async()=>{
 const f=await fixture();await seed(f);const app=express();app.use(express.json());for(const [key,handler]of f.routes){const [method,...parts]=key.split(' ');app[method.toLowerCase()](parts.join(' '),handler);}app.use(express.static(path.resolve(__dirname,'..')));
 const server=await new Promise(r=>{const s=app.listen(0,'127.0.0.1',()=>r(s));});let browser;
 try{
  browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_EXECUTABLE||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});const page=await browser.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route('**/*',r=>new URL(r.request().url()).hostname==='127.0.0.1'?r.continue():r.abort());await page.goto('http://127.0.0.1:'+server.address().port);
  const ready=()=>page.waitForFunction(()=>!document.querySelector('#wr-results').hidden&&document.querySelector('#wr-status').textContent.includes('集計しました'));
  const stats=n=>page.waitForFunction(n=>!document.querySelector('#wr-results').hidden&&document.querySelector('#wr-search-stats').textContent.startsWith(n+'試合'),n);
  for(const width of [375,390,430,768,1440]){
   await page.setViewportSize({width,height:900});if(width<=720)await page.locator('#menu-more').click();await page.locator('#menu-winrate').click();await ready();
   await page.locator('#wr-search-mode').selectOption('deck');await page.waitForFunction(()=>document.querySelector('#wr-status').textContent.includes('デッキAを選択'));
   assert.equal(await page.locator('#wr-deck-b-field').isVisible(),false);await page.locator('#wr-deck-a-query').fill('別名A');assert.equal(await page.locator('#wr-deck-a option').count(),2);assert.equal(await page.locator('#wr-deck-a option').nth(1).textContent(),'A');await page.locator('#wr-deck-a').selectOption('1');await stats(6);assert.equal(await page.locator('#wr-decks tr').count(),1);assert.equal(await page.locator('#wr-search-events tr').count(),3);assert.equal(await page.locator('#wr-search-opponents tr').count(),1);
   await page.locator('#wr-search-details').click();await page.waitForFunction(()=>document.querySelector('#wr-detail-status').textContent.includes('6試合'));assert.equal(await page.locator('#wr-detail-matches article').count(),6);await page.locator('#wr-detail-close').click();
   await page.locator('#wr-search-mode').selectOption('matchup');await page.locator('#wr-deck-b-query').fill('B');await page.locator('#wr-deck-b').selectOption('2');await stats(6);assert.equal(await page.locator('#wr-matrix-head th').count(),2);assert.equal(await page.locator('#wr-matrix-body tr').count(),1);
   await page.locator('#wr-mode').selectOption('single');await page.locator('#wr-event').selectOption('2');await stats(2);await page.locator('#wr-start').fill('2026-10-02');await page.locator('#wr-end').fill('2026-10-02');await page.locator('#wr-format').selectOption('advance');await stats(2);
   await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:'/tmp/winrate-search-'+width+'.png',fullPage:true});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'page overflow '+width);
   await page.locator('#wr-deck-b-query').fill('C');await page.locator('#wr-deck-b').selectOption('3');await page.waitForFunction(()=>document.querySelector('#wr-status').textContent==='該当する対戦データがありません。');assert.equal(await page.locator('#wr-search-details').isEnabled(),false);
   await page.locator('#wr-search-clear').click();await ready();assert.equal(await page.locator('#wr-search-results').isVisible(),false);assert.equal(await page.locator('#wr-mode').inputValue(),'single');assert.equal(await page.locator('#wr-format').inputValue(),'advance');
   await page.locator('#wr-mode').selectOption('all');await page.locator('#wr-start').fill('');await page.locator('#wr-end').fill('');await page.locator('#wr-format').selectOption('');await page.locator('#menu-deck-memo').click();console.log('PASS '+width+'px: alias candidates, deck/pair search, combined filters, details, zero, clear and layout');
  }
  await page.locator('#menu-winrate').click();await ready();await page.locator('#wr-search-mode').selectOption('deck');await page.locator('#wr-deck-a').selectOption('1');await stats(6);
  // Real memo API update; searching again must read current data, including missing opponent.
  await page.evaluate(async()=>{const r=await fetch('/api/deck-memo',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({url:'https://nojigikucs.com/?admin=noji',memoEventId:1,dmpId:'456',deckId:null})});if(!r.ok)throw Error('memo clear failed');});
  await page.locator('#wr-reload').click();await stats(6);await page.waitForFunction(()=>document.querySelector('#wr-search-gap').textContent.includes('2試合・1勝1敗'));assert.ok((await page.locator('#wr-search-opponents').textContent()).includes('4'));await page.locator('#wr-search-details').click();await page.waitForFunction(()=>document.querySelector('#wr-detail-matches').textContent.includes('デッキ不明'));
  await page.evaluate(async()=>{for(const [id,deckId] of [['000123',2],['456',2]]){const r=await fetch('/api/deck-memo',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({url:'https://nojigikucs.com/?admin=noji',memoEventId:1,dmpId:id,deckId})});if(!r.ok)throw Error('memo update failed');}});
  await page.locator('#wr-search-mode').selectOption('matchup');await page.locator('#wr-deck-a').selectOption('2');await page.locator('#wr-deck-b').selectOption('2');await stats(2);assert.ok((await page.locator('#wr-search-stats').textContent()).includes('2勝 2敗 ／ 50.0%'));await page.locator('#wr-search-details').click();await page.waitForFunction(()=>document.querySelector('#wr-detail-status').textContent.includes('2試合 ／ 2勝 2敗'));assert.equal(await page.locator('#wr-detail-matches article').count(),2);
  await page.locator('#wr-deck-a').selectOption('1');await page.locator('#wr-deck-b').selectOption('2');await stats(4);const forward=await page.locator('#wr-search-stats').textContent();await page.locator('#wr-deck-a').selectOption('2');await page.locator('#wr-deck-b').selectOption('1');await stats(4);assert.equal(forward,await page.locator('#wr-search-stats').textContent());
  assert.deepEqual(errors,[]);console.log('PASS current memo updates, unknown-opponent gap/details, mirror count, reversed matchup, no page errors');
 }finally{await browser?.close();await new Promise(r=>server.close(r));await f.db.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
