CREATE TABLE IF NOT EXISTS deck_memo_events (
  id SERIAL PRIMARY KEY,
  source TEXT NOT NULL DEFAULT 'nojigiku',
  admin_key VARCHAR(100) NOT NULL,
  source_url TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (source, admin_key)
);
CREATE TABLE IF NOT EXISTS deck_memos (
  id SERIAL PRIMARY KEY,
  memo_event_id INTEGER NOT NULL REFERENCES deck_memo_events(id) ON DELETE RESTRICT,
  dmp_id VARCHAR(50) NOT NULL,
  player_id INTEGER REFERENCES players(id) ON DELETE SET NULL,
  deck_id INTEGER NOT NULL REFERENCES decks(id) ON DELETE RESTRICT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (memo_event_id, dmp_id)
);
CREATE INDEX IF NOT EXISTS deck_memos_deck_idx ON deck_memos(deck_id);
